package org.eclipse.ice.apps.wizard;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.annotations.DesignRoot;
import com.vaadin.ui.CheckBox;
import com.vaadin.ui.Label;
import com.vaadin.ui.TextField;
import com.vaadin.ui.VerticalLayout;
import com.vaadin.ui.declarative.Design;

/** 
 * !! DO NOT EDIT THIS FILE !!
 * 
 * This class is generated by Vaadin Designer and will be overwritten.
 * 
 * Please make a subclass with logic and additional interfaces as needed,
 * e.g class LoginView extends LoginDesign implements View { }
 */
@DesignRoot
@AutoGenerated
@SuppressWarnings("serial")
public class DockerDesign extends VerticalLayout {
	protected TextField txtFieldContainerName;
	protected TextField txtFieldContainerPorts;
	protected TextField txtFieldContainerVolumes;
	protected CheckBox chkBoxIsEphemeral;
	protected Label dummyLabelForSpace;

	public DockerDesign() {
		Design.read(this);
	}
}
